### ISSUE TITLE
ParsedURL does not respect http.agent system property

### ISSUE THREAD

**Issue by DaveJarvis** [css4j/echosvg#2]
See: https://issues.apache.org/jira/browse/BATIK-1300

The fix is to change `org.apache.batik.util.ParsedURL`, around line 90, to set `globalUserAgent` using the `http.agent` value. If the `http.agent` value is not set, fall back to a default (e.g., maintain backwards comparability).

**Comment by carlosame** [comment]
I'm thinking of something like this:

```patch
@@ -83,11 +83,15 @@ public class ParsedURL {
 	 * The default protocol handler. This handler is used when other handlers fail
 	 * or no match for a protocol can be found.
 	 */
 	private static ParsedURLProtocolHandler defaultHandler = new ParsedURLDefaultProtocolHandler();
 
-	private static String globalUserAgent = "EchoSVG/0.1";
+	private static String globalUserAgent;
+
+	static {
+		globalUserAgent = System.getProperty("http.agent", "EchoSVG/0.1");
+	}
 
 	public static String getGlobalUserAgent() {
 		return globalUserAgent;
 	}
 ```
That is, changes to `http.agent` once the class was loaded would not be honored (otherwise it makes little sense to have a `setGlobalUserAgent`, not to talk of considerations about performance and consistency across requests).

Would that fit your needs?

**Comment by carlosame** [comment]
Github closed this automatically after my commit, reopening so you can comment on the applied solution and possible further cleanups.

**Comment by DaveJarvis** [comment]
Looks good.
