### ISSUE TITLE
Support the `transparent` color identifier

### ISSUE THREAD

**Issue by carlosame** [css4j/echosvg#47]
Given that this software supports colors with an alpha channel, it should support the `transparent` color identifier as well:

https://www.w3.org/TR/css-color-3/#transparent

**Comment by i-make-robots** [comment]
will this be in 0.2.1?

**Comment by carlosame** [comment]
> When will 0.2.1 be out, please?

![milestone](https://user-images.githubusercontent.com/38894633/180497549-e6084a72-69eb-4773-86eb-8ff330ec019d.png)

Would you like to see it released earlier?
