### ISSUE TITLE
Externalize application version

### ISSUE THREAD

**Issue by DaveJarvis** [css4j/echosvg#5]
Consider placing the version in an external file that can be read from both the build system during build time and application at runtime. Maven has at least one plugin can export Git repo details into a POJO or properties file:

https://github.com/git-commit-id/git-commit-id-maven-plugin#getting-snapshot-versions-of-the-plugin

**Comment by carlosame** [comment]
Any solution would have to sync the version obtained from the `git-commit-id` plugin with the `<version>` tag in the various POM files. Apparently the plugin does not do that update automatically, and an external script would imply that we would not have a single-step build. Or perhaps this is not needed and I missed something (I looked at the plugin docs really fast).

As a side note, you may notice that the `-SNAPSHOT` prefix is not used in the POM files of EchoSVG: using that prefix would cause undesired requests to the Maven Central repository, which is not used by this project.

**Comment by DaveJarvis** [comment]
Note: relates to `ParsedURL`'s `globalUserAgent` method.

**Comment by carlosame** [comment]
> See also ParsedURL's globalUserAgent member variable, which has a hard-coded version number.

I wonder if `Mozilla/4.0 (compatible; EchoSVG)` would be a better UA string, and not waste CPU cycles in adding a version that probably no server is going to care about (except for vulnerability profiling...).

**Comment by DaveJarvis** [comment]
> a better UA string

Yes.

**Comment by carlosame** [comment]
Default UA string modified by commit [1b5c2a96].
