### ISSUE TITLE
Separate build steps into BUILD.md

### ISSUE THREAD

**Issue by DaveJarvis** [css4j/echosvg#7]
> It is better to have them displayed at the Github's project homepage. Most projects have it that way.

Leaving _argumentum ad populum_ aside, at the very least we'll want to have a clearly enumerated set of instructions. For example:

---

# Building

This section defines how to build the library.

## Requirements

Download then install the following software packages:

* Java version X
* Maven version X
* Git version X
* JCLF
* CSS4J

## Install dependencies (Linux)

Install the software dependencies for the first time as follows:

1. wget https://raw.githubusercontent.com/css4j/css4j-dist/master/install-jclf.sh
1. sh install-jclf.sh
1. wget https://raw.githubusercontent.com/css4j/css4j-dist/master/install-css4j.sh
1. sh install-css4j.sh

The dependencies of JCLF and CSS4J are installed.

## Build library

Build the library as follows:

1. git clone https://github.com/css4j/echosvg
1. cd echosvg
1. mvn package

The library is built as `path/to/file.jar`.

----

From here, we'll need additional instructions showing how to build variations.

At this point, it's trivial to see how we could have a `build.sh` script that installs the Maven dependencies on behalf of the end user. That, eventually, could lead to a Maven (arguably easier with Gradle) integration in the `pom.xml` file.

**Comment by carlosame** [comment]
I'm not separating the build instructions to a BUILD.md but I have made the README build instructions more verbose.

Is that an improvement?

**Comment by DaveJarvis** [comment]
The documentation looks _much_ better.
